version: "2"
services:
  dockergen:
    depends_on:
      - nginx
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    restart: always
    container_name: dockergen
  db:
    depends_on:
      - nginx
    image: mysql:5.7
    volumes:
      - /opt/docker-volume/mysql-gitea:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: o$su876HG@zvsRt3BT
      MYSQL_DATABASE: gitteadb
      MYSQL_USER: gittea-user
      MYSQL_PASSWORD: 34@zv$TKji@s097BB
    container_name: gitea-db

  nginx:
    image: nginx
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/htpasswd:/etc/ngninx/htpasswd
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /etc/nginx/certs:/nginx/certs
    container_name: nginx
    ports:
      - "80:80"
    restart: always

  gitea:
    depends_on:
      - db
    image: gitea/gitea:1.8
    volumes:
      - /opt/docker-volume/gitea-selfhosted:/data
    ports:
      - "3000:3000"
    container_name: gitea
    environment:
      VIRTUAL_HOST: gitea.local
      VIRTUAL_PORT: 3000
      USER_UID: 1001
      USER_GID: 1001
      DB_TYPE: mysql
      DB_HOST: db:3306
      DB_NAME: gitteadb
      DB_USER: gittea-user
      DB_PASSWD: 34@zv$TKji@s097BB
    restart: always
